/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import cadastroseresvivos.Animal;
import cadastroseresvivos.SVivo;
import cadastroseresvivos.Vegetal;
import com.sun.glass.events.KeyEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author marco
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */

    private ArrayList<Animal> listaAnimais =new ArrayList<Animal>();
    private ArrayList<Vegetal> listaVegetal = new ArrayList<Vegetal>();
    
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoArquivo = new javax.swing.ButtonGroup();
        grupoTipoSer = new javax.swing.ButtonGroup();
        grupoPorte = new javax.swing.ButtonGroup();
        grupoFrutifera = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txLocal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rdTxt = new javax.swing.JRadioButton();
        rdJson = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdAnimal = new javax.swing.JRadioButton();
        rdVegetal = new javax.swing.JRadioButton();
        lbNumeroPatas = new javax.swing.JLabel();
        txtNumeroPatas = new javax.swing.JTextField();
        lbClasse = new javax.swing.JLabel();
        txtClasse = new javax.swing.JTextField();
        lbPorte = new javax.swing.JLabel();
        rdGrande = new javax.swing.JRadioButton();
        rdMedio = new javax.swing.JRadioButton();
        rdPequeno = new javax.swing.JRadioButton();
        lbFrutifera = new javax.swing.JLabel();
        rdNao = new javax.swing.JRadioButton();
        rdSim = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        lbDiretorio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Local de Origem");

        jLabel4.setText("Tipo");

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Gerar Aquivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        grupoTipoArquivo.add(rdTxt);
        rdTxt.setText(".TXT");

        grupoTipoArquivo.add(rdJson);
        rdJson.setText("JSON");

        jLabel5.setText("Formato do Arquivo");

        grupoTipoSer.add(rdAnimal);
        rdAnimal.setText("Animal");
        rdAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdAnimalMouseClicked(evt);
            }
        });
        rdAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAnimalActionPerformed(evt);
            }
        });

        grupoTipoSer.add(rdVegetal);
        rdVegetal.setText("Vegetal");
        rdVegetal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdVegetalMouseClicked(evt);
            }
        });

        lbNumeroPatas.setText("Numero de Patas");
        lbNumeroPatas.setVisible(false);

        txtNumeroPatas.setToolTipText("");
        txtNumeroPatas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroPatasKeyTyped(evt);
            }
        });
        txtNumeroPatas.setVisible(false);

        lbClasse.setText("Classe");

        lbPorte.setText("Porte");

        grupoPorte.add(rdGrande);
        rdGrande.setText("Grande");

        grupoPorte.add(rdMedio);
        rdMedio.setText("Médio");

        grupoPorte.add(rdPequeno);
        rdPequeno.setText("Pequeno");

        lbFrutifera.setText("Frutífera");

        grupoFrutifera.add(rdNao);
        rdNao.setText("Não");

        grupoFrutifera.add(rdSim);
        rdSim.setText("Sim");

        jButton3.setText("Selecionar Diretório");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtClasse))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtNumeroPatas))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(rdAnimal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNumeroPatas)
                                    .addComponent(lbClasse))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbPorte)
                                            .addComponent(rdVegetal)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(lbFrutifera)))
                                .addGap(0, 58, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(rdMedio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdPequeno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdNao))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdGrande)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(txNome)
                                        .addComponent(jLabel3)
                                        .addComponent(txLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(173, 173, 173)
                                    .addComponent(jLabel4))
                                .addComponent(rdTxt)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap(4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(Cadastrar))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbDiretorio)
                                    .addComponent(rdJson))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdAnimal)
                    .addComponent(rdVegetal))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeroPatas)
                    .addComponent(lbPorte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroPatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdGrande)
                    .addComponent(rdMedio)
                    .addComponent(rdPequeno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClasse)
                    .addComponent(lbFrutifera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdNao)
                    .addComponent(rdSim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cadastrar)
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdJson)
                .addGap(6, 6, 6)
                .addComponent(lbDiretorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        lbClasse.setVisible(false);
        txtClasse.setVisible(false);
        lbPorte.setVisible(false);
        rdGrande.setVisible(false);
        rdMedio.setVisible(false);
        rdPequeno.setVisible(false);
        lbFrutifera.setVisible(false);
        rdNao.setVisible(false);
        rdSim.setVisible(false);

        jLabel1.setText("Cadastro Seres Vivos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroPatasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroPatasKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE )){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroPatasKeyTyped

    private void rdVegetalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdVegetalMouseClicked
        lbNumeroPatas.setVisible(false);
        txtNumeroPatas.setVisible(false);
        lbClasse.setVisible(false);
        txtClasse.setVisible(false);
        lbPorte.setVisible(true);
        rdGrande.setVisible(true);
        rdMedio.setVisible(true);
        rdPequeno.setVisible(true);
        lbFrutifera.setVisible(true);
        rdSim.setVisible(true);
        rdNao.setVisible(true);

    }//GEN-LAST:event_rdVegetalMouseClicked

    private void rdAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAnimalActionPerformed

    private void rdAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdAnimalMouseClicked
        lbNumeroPatas.setVisible(true);
        txtNumeroPatas.setVisible(true);
        lbClasse.setVisible(true);
        txtClasse.setVisible(true);
        lbPorte.setVisible(false);
        rdGrande.setVisible(false);
        rdMedio.setVisible(false);
        rdPequeno.setVisible(false);
        lbFrutifera.setVisible(false);
        rdSim.setVisible(false);
        rdNao.setVisible(false);
    }//GEN-LAST:event_rdAnimalMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        if (rdAnimal.isSelected()&&
                (!txtNumeroPatas.getText().equals(""))&&
                (!txtClasse.getText().equals(""))&&
                (!txNome.getText().equals(""))&&
                (!txLocal.getText().equals(""))) {
            Animal animal = new Animal();
            animal.setNome(txNome.getText());
            animal.setLocalOrigem(txLocal.getText());
            animal.setNumeroPatas(Integer.parseInt(txtNumeroPatas.getText()));
            animal.setClasse(txtClasse.getText());
            animal.setReproducao(reproducao());
            for (Animal listaAnimal : listaAnimais) {
                if(listaAnimal.getNome().equals(animal.getNome())){
                    JOptionPane.showMessageDialog(null, "Nome já existente!");
                    return;
                }
            }
            listaAnimais.add(animal);
            return;
        }else if(rdAnimal.isSelected()){
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos");
            
        }
        if (rdVegetal.isSelected()&&
                (rdGrande.isSelected()||rdMedio.isSelected()||rdPequeno.isSelected())&&
                (rdSim.isSelected()||rdNao.isSelected())&&
                (!txLocal.getText().equals(""))) {
            Vegetal vegetal = new Vegetal();
            vegetal.setNome(txNome.getText());
            vegetal.setLocalOrigem(txLocal.getText());
            vegetal.setPorte(converter("porte"));
            vegetal.setTipo(converter("tipo"));
            vegetal.setReproducao(reproducao());
            for (Vegetal listaVegetal : listaVegetal) {
                if(listaVegetal.getNome().equals(vegetal.getNome())){
                    JOptionPane.showMessageDialog(null, "Nome já existente!");
                    return;
                }
            }
            listaVegetal.add(vegetal);
            return;
        }else if(rdVegetal.isSelected()){
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos");
        }

    }//GEN-LAST:event_CadastrarActionPerformed
    
    private String converter(String formato){
        if(formato.equals("porte")){
            if(rdGrande.isSelected()){
                return "Grande";
            }
            if(rdMedio.isSelected()){
                return "GMedio";
            }
            if(rdPequeno.isSelected()){
                return "Pequeno";
            }
        }
        if(formato.equals("tipo")){
            if(rdSim.isSelected()){
                return "sim";
            }
            if(rdPequeno.isSelected()){
                return "nao";
            }
        }
        return null;
    }
    
    private String reproducao(){
        if((rdAnimal.isSelected())||((rdVegetal.isSelected())&&rdSim.isSelected())){
        return "sexuada";
        }
        if((rdVegetal.isSelected())&&rdNao.isSelected()){
           return "assexuada";
        }
        return null;
    }
    
    private void txNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(rdJson.isSelected()){
            try (
            FileWriter file = new FileWriter(lbDiretorio.getText()+"/ArquivoJSON.json")) {
            for (Animal animal : listaAnimais) {
                JSONObject obj = new JSONObject();
                obj.put("Nome", animal.getNome());
                obj.put("Regiao", animal.getLocalOrigem());
                obj.put("Tipo","Animal");
                obj.put("NumeroDePatas", animal.getNumeroPatas()+"");
                obj.put("Classe", animal.getClasse());
                obj.put("Reproducao",animal.getReproducao());
                file.write(obj.toString());
            }
            for (Vegetal vegetal : listaVegetal) {
                JSONObject obj = new JSONObject();
                obj.put("Nome", vegetal.getNome());
                obj.put("Regiao", vegetal.getLocalOrigem());
                obj.put("Tipo","Vegetal");
                obj.put("Porte", vegetal.getPorte());
                obj.put("Frutifero", vegetal.getTipo());
                obj.put("Reproducao",vegetal.getReproducao());
                file.write(obj.toString());
            }
            JOptionPane.showMessageDialog(null, "Arquivo JSON Salvo com Sucesso!!");
            } catch (IOException ex) {

            }
        }
        
        if(rdTxt.isSelected()){
            try (
            FileWriter file = new FileWriter(lbDiretorio.getText()+"/ArquivoTXT.txt")) {
            for (Animal animal : listaAnimais) {
                JSONObject obj = new JSONObject();
                obj.put("Nome", animal.getNome());
                obj.put("Regiao", animal.getLocalOrigem());
                obj.put("Tipo","Animal");
                obj.put("NumeroDePatas", animal.getNumeroPatas()+"");
                obj.put("Classe", animal.getClasse());
                obj.put("Reproducao",animal.getReproducao());
                file.write(obj.toString());
            }
            for (Vegetal vegetal : listaVegetal) {
                JSONObject obj = new JSONObject();
                obj.put("Nome", vegetal.getNome());
                obj.put("Regiao", vegetal.getLocalOrigem());
                obj.put("Tipo","Vegetal");
                obj.put("Porte", vegetal.getPorte());
                obj.put("Frutifero", vegetal.getTipo());
                obj.put("Reproducao",vegetal.getReproducao());
                file.write(obj.toString());
            }
            JOptionPane.showMessageDialog(null, "Arquivo JSON Salvo com Sucesso!!");
            } catch (IOException ex) {

            }
        }
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser selecionarDir = new JFileChooser();
        selecionarDir.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selecao = selecionarDir.showOpenDialog(this);
        if(selecao == JFileChooser.APPROVE_OPTION){
            lbDiretorio.setText(selecionarDir.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.ButtonGroup grupoFrutifera;
    private javax.swing.ButtonGroup grupoPorte;
    private javax.swing.ButtonGroup grupoTipoArquivo;
    private javax.swing.ButtonGroup grupoTipoSer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbClasse;
    private javax.swing.JLabel lbDiretorio;
    private javax.swing.JLabel lbFrutifera;
    private javax.swing.JLabel lbNumeroPatas;
    private javax.swing.JLabel lbPorte;
    private javax.swing.JRadioButton rdAnimal;
    private javax.swing.JRadioButton rdGrande;
    private javax.swing.JRadioButton rdJson;
    private javax.swing.JRadioButton rdMedio;
    private javax.swing.JRadioButton rdNao;
    private javax.swing.JRadioButton rdPequeno;
    private javax.swing.JRadioButton rdSim;
    private javax.swing.JRadioButton rdTxt;
    private javax.swing.JRadioButton rdVegetal;
    private javax.swing.JTextField txLocal;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextField txtNumeroPatas;
    // End of variables declaration//GEN-END:variables

    private void If(boolean selected) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
